import { definePromptTemplate } from './template-registry'

export const PROMPT_TEMPLATES = {
  titleStudio: definePromptTemplate({ id: 'title-studio.generate', version: 'v1.0', locale: 'hu-HU', description: 'Öt eltérő magyar címváltozat és AI-értékelés.' }),
  keywordCluster: definePromptTemplate({ id: 'keyword-research.cluster', version: 'v1.0', locale: 'hu-HU', description: 'Long-tail kulcsszóklaszter valós keresési jelekből.' }),
  contentGap: definePromptTemplate({ id: 'content-gap.discover', version: 'v2.0', locale: 'hu-HU', description: 'Tartalmi rések konkrét YouTube- és Google-jelek bizonyítékkötött összevetésével.' }),
  channelNicheDiscovery: definePromptTemplate({ id: 'channel_niche_discovery', version: 'v1', locale: 'hu-HU', description: 'Channel niche discovery.' }),
  channelAuditNextVideos: definePromptTemplate({ id: 'channel_audit_next_videos', version: 'v1', locale: 'hu-HU', description: 'Next-video recommendations from channel audit.' }),
  similarVideosQueryExpansion: definePromptTemplate({ id: 'similar_videos_query_expansion', version: 'v1', locale: 'hu-HU', description: 'Similar-video query expansion.' }),
  trendRadarTopicRewrite: definePromptTemplate({ id: 'trend_radar_topic_rewrite', version: 'v1', locale: 'hu-HU', description: 'Trend Radar query shortening.' }),
  opportunityEngineExplanations: definePromptTemplate({ id: 'opportunity_engine_explanations', version: 'v1', locale: 'hu-HU', description: 'Opportunity candidate explanations.' }),
  opportunityExplainPool: definePromptTemplate({ id: 'opportunity_explain_pool', version: 'v1', locale: 'hu-HU', description: 'Opportunity evidence-pool explanation.' }),
  opportunityExplainSimilar: definePromptTemplate({ id: 'opportunity_explain_similar', version: 'v1', locale: 'hu-HU', description: 'Alternative angle from the same evidence.' }),
  seoOptimizerPackage: definePromptTemplate({ id: 'seo_optimizer_package', version: 'v1', locale: 'hu-HU', description: 'SEO package generation.' }),
  thumbnailStudioConcepts: definePromptTemplate({ id: 'thumbnail_studio_concepts', version: 'v1', locale: 'hu-HU', description: 'Thumbnail concept generation.' }),
  scriptExtractTranscript: definePromptTemplate({ id: 'script_extract_transcript', version: 'v1', locale: 'hu-HU', description: 'Structure analysis from transcript.' }),
  scriptExtractMetadata: definePromptTemplate({ id: 'script_extract_metadata_only', version: 'v1', locale: 'hu-HU', description: 'Estimated structure analysis from metadata.' }),
  videoAuditInterpretation: definePromptTemplate({ id: 'video_audit_interpretation', version: 'v1', locale: 'hu-HU', description: 'Qualitative video-audit interpretation.' }),
  videoPackageCoreShorts: definePromptTemplate({ id: 'video_package_core_shorts', version: 'v1', locale: 'hu-HU', description: 'Short-form video package core.' }),
  videoPackageCoreLong: definePromptTemplate({ id: 'video_package_core_long', version: 'v1', locale: 'hu-HU', description: 'Long-form video package core.' }),
  videoPackagePackaging: definePromptTemplate({ id: 'video_package_packaging', version: 'v2', locale: 'hu-HU', description: 'Marketing packaging and upload checklist.' }),
  videoPackageOrchestration: definePromptTemplate({ id: 'video_package', version: 'v1', locale: 'hu-HU', description: 'Video package orchestration version.' }),
  viralScoreExplanation: definePromptTemplate({ id: 'viral_score_explanation', version: 'v1', locale: 'hu-HU', description: 'Backend Viral Score explanation.' }),
  seedGenerator: definePromptTemplate({ id: 'seed_generator', version: 'v2', locale: 'hu-HU', description: 'Dynamic creator-intelligence search seeds.' }),
} as const
